version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - echo Logging...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 586794469892.dkr.ecr.us-east-1.amazonaws.com
      - echo Setting repo URI...
      - REPOSITORY_URI=586794469892.dkr.ecr.us-east-1.amazonaws.com/backend-imagenes
      - echo Setting image tag...
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo building and tagging image
      - echo running mvn clean install
      - mvn clean install
      - echo building Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo tagging docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing Docker image to ECR
      - echo pushing to repo...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo setting container name...
      - DOCKER_CONTAINER_NAME=backendcontainer
      - echo writing image def file
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing def file
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
